from .nilornodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .image_stream_input import NODE_CLASS_MAPPINGS as is_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as is_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS.update(is_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(is_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
